version: '3.0'
services:
  app:
    build: .
    ports:
      -   8080:80
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Map the init.sql file
    ports:
      -  5432:5432