version: '3.9'
version: '3.9'
services:
  db:
    image: postgres:latest
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5555:5432"
  
  app:
      - "5555:5432"
  
  app:
    depends_on:
      - db
    build: .
    ports:
      - 5000:5000
    environment:
      SECRET_KEY: ${SECRET_KEY}

      - 5000:5000
    environment:
      SECRET_KEY: ${SECRET_KEY}

    restart: always

volumes:
  data: