version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5555:5432"  # Port 5432 i dockerconteiner, Port 5555 utad
  
  app:
    depends_on:
      - db
    build: .
    ports:
      - 5556:5000   # Port 5000 i dockerconteiner, Port 5556 utad
    environment:
      SECRET_KEY: ${SECRET_KEY}
    restart: always