version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Map the init.sql file
    ports:
      -  5432:5432
  flask_app:
    depends_on:
      - db
    build: .
    ports:
      - "8081:8081"
      - "4431:443"
    restart: always