version: '3.0'
services:
  app:
    build: .
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    depends_on:
      - db
  db:
    image: postgres
    container_name: ${DATABASE_NAME}
    restart: always
    environment:
      POSTGRES_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Map the init.sql file
    ports:
      - "5432:5432"
