name: 'Get & Cache dependencies'
description: 'Get the dependencies (poetry) and cache them.'
inputs:
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:

    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: Install the project dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: poetry install
      shell: bash